// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qolgkndudohwxiazopcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbGdrbmR1ZG9od3hpYXpvcGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTMxNDUsImV4cCI6MjA2NzQ2OTE0NX0.v3n7R93_yaMdPy7aGyfUT1XZN9asYgWFtafnqqEh1hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});